name: SonarQube Analysis
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Java 17 compiler args
      run: |
        mvn clean compile -Dmaven.compiler.source=17 -Dmaven.compiler.target=17
        
    - name: Run Tests and Generate Coverage
      run: |
        mvn test jacoco:report -Dmaven.compiler.source=17 -Dmaven.compiler.target=17
        
    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=it-ideatask \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dmaven.compiler.source=17 -Dmaven.compiler.target=17
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
